### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-analytics#17]
- after succesful Auth0 authentication error message says `invalid token`
<img width="1280" alt="screen shot 2018-02-06 at 9 44 07 am" src="https://user-images.githubusercontent.com/944642/35871279-d5f90d3e-0b31-11e8-8279-d3d80149b430.png">

- or, does not redirect from callback page to dashboard

Advice is not to use Firefox.

**Comment by tomasholderness** [comment]
Also Safari.

**Comment by ojha-url** [comment]
Potential fix:
https://github.com/urbanriskmap/cognicity-analytics/blob/master/src/environments/environment.prod.ts#L9

Change callback address to https://...

Should test after creating a separate staging build (dashboard-dev.petabencana.id) and move prod to (dashboard.petabencana.id)

**Comment by matthewberryman** [comment]
Yeah I put that fix in but it's not deployed as I forgot the webhook was broken.

**Comment by matthewberryman** [comment]
Ok there is some confusion here between two different issues. The screenshot was for an issue affecting all browsers (incl. Chrome, hence rename of this issue) because of incorrect url (now fixed per above discussion). There's a separate issue in Firefox (but not Safari, as one would expect as Safari and Chrome are webkit based but Firefox is not) that I will open soon.

Once I hear back from field office there's a separate issue to refine what we're doing with dev environment.
